<div className="row text-center paddingtopbottom5px">
												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_int.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.startInt} + {hero.IntPerLv}
													</div>
												</div>

												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_attack.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.minDmgLv1} - {hero.maxDmgLv1}
													</div>
												</div>
											</div>

											<div className="row text-center paddingtopbottom5px">
												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_agi.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.startAgi} + {hero.AgiPerLv}
													</div>
												</div>

												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_speed.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.speed}
													</div>
												</div>
											</div>

											<div className="row text-center paddingtopbottom5px">
												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_str.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.startStr} + {hero.StrPerLv}
													</div>
												</div>

												<div className="col-xs-12 col-md-6">
													<div className="col-xs-12 col-md-4" >
														<img className="" src={"build/picture/dotahero/basicIcons/overviewicon_armor.png"} alt />
													</div>
													<div className="col-xs-12 col-md-8 text-left" >
														{hero.armor}
													</div>
												</div>
											</div>